.travis.yml:

before_script:
  - npm install
  - mysql -u root -e 'create database if not exists travis_db;'
  - mysql -u root travis_db < test.sql

  test:
    database: 'travis_db'
    username: 'root'
    password: null

env:
  - MYSQL_PWD = null

script: mocha
